[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_TURBOPACK = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]
