[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions/"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    functions_src = ".netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]
